name: documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-design sphinx_copybutton pydata-sphinx-theme
      - name: Sphinx build
        run: |
          sphinx-build docs _build

      - name: Copy .sh file to build directory
        run: |
          cp docs/installer.sh docs/_build/html/installer.sh
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.1.0
        with:
          branch: master
          dir_docs: docs
          sphinx-apidoc: false
          
