name: Auto Dev Version Bumper

on:
    push:
        branches:
            - master
permissions:
    contents: write 

jobs:
    version-bump:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0 
                    persist-credentials: true

            -   name: Run auto-dev-version-bumper
                if: ${{ !contains(github.event.head_commit.message, 'Bump version to') && !contains(github.event.head_commit.message, 'Update badge') && !contains(github.event.head_commit.message, 'no bump') }}
                uses: LorenzoMugnai/auto-dev-version-bumper@1.1
                with:
                    dev_suffix: "-beta"
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
                    GITHUB_SHA: ${{ github.event.after }}
                    
            -   name: Read version
                id: read_version
                run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

            -   name: Create Badge
                uses: sebymiano/shields-badge-generator@v1.0.4
                with:
                    label: 'Version'
                    status: ${{ env.VERSION }}
                    color: 'blue'
                    logo: 'github'
                    path: 'content/version.svg'

            -   name: Ensure Git permissions
                run: sudo chmod -R u+rw .git

            -   name: Commit and push badge
                run: |
                    git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                    git config --global user.name "github-actions[bot]"
                    git add content/version.svg
                    git commit -m "Update badge" || echo "No changes to commit"
                    git push origin HEAD
