name: Auto Dev Version Bumper

on:
    push:
        branches:
            - master
permissions:
    contents: write 

jobs:
    version-bump:
        if: ${{ !contains(github.event.head_commit.message, 'Bump version to') && !contains(github.event.head_commit.message, 'Update badge') && !contains(github.event.head_commit.message, 'no bump') }}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0 
                    persist-credentials: true

            -   name: Run auto-dev-version-bumper
                uses: LorenzoMugnai/auto-dev-version-bumper@1.1
                with:
                    dev_suffix: "-beta"
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
                    GITHUB_SHA: ${{ github.event.after }}
                    
            -   name: Read version
                id: read_version
                run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

            -   name: Create Badge
                uses: sebymiano/shields-badge-generator@v1.0.4
                with:
                    label: 'Version'
                    status: ${{ env.VERSION }}
                    color: 'blue'
                    logo: 'github'
                    path: 'content/version.svg'

            -   name: Upload badge as artifact
                uses: actions/upload-artifact@v4
                with:
                    name: badge
                    path: 'content/version.svg'
                    if-no-files-found: error
            
            -   name: Commit and push badge
                uses: stefanzweifel/git-auto-commit-action@v5
                with:
                    commit_message: "Update badge"
